from typing import Any, Callable, Dict, List, Optional, Tuple

class UniversalEvent:
    id: str
    chat_id: str
    user_id: str
    text: str
    platform: str
    event_type: str
    command: str
    args: List[str]
    raw: str
    metadata: Dict[str, str]
    timestamp: float

    def __init__(
        self,
        id: str = ...,
        chat_id: str = ...,
        user_id: str = ...,
        text: str = ...,
        platform: str = ...,
        event_type: str = ...,
        command: str = ...,
        args: Optional[List[str]] = ...,
        raw: str = ...,
        metadata: Optional[Dict[str, str]] = ...,
        timestamp: Optional[float] = ...,
    ) -> None: ...

class Dispatcher:
    def __init__(self) -> None: ...
    def add_command_handler(self, command: str, handler_id: str) -> None: ...
    def add_pattern_handler(self, pattern: str, handler_id: str) -> None: ...
    def add_event_handler(self, event_type: str, handler_id: str) -> None: ...
    def add_state_handler(self, state_name: str, handler_id: str) -> None: ...
    def match(self, event: UniversalEvent, current_state: str = ...) -> List[str]: ...
    def parse_telegram(self, json_str: str) -> UniversalEvent: ...
    def parse_discord(self, json_str: str) -> UniversalEvent: ...
    def parse_generic(self, json_str: str, platform: str = ...) -> UniversalEvent: ...
    @staticmethod
    def extract_command_and_args(text: str) -> Tuple[str, List[str]]: ...

class RateLimiter:
    def __init__(self) -> None: ...
    def set_rule(self, scope: str, rate_str: str) -> None: ...
    def set_custom_rule(self, scope: str, capacity: float, window_seconds: float) -> None: ...
    def acquire(self, key: str, tokens: float = ...) -> bool: ...
    def check(self, key: str, tokens: float = ...) -> Tuple[bool, float]: ...
    def check_and_acquire(self, user_id: str, chat_id: str, tokens: float = ...) -> Tuple[bool, float]: ...
    def record_429(self, key: str, retry_after_seconds: float) -> None: ...
    def get_retry_after(self, key: str) -> float: ...
    def reset(self, key: str = ...) -> None: ...
    def size(self) -> int: ...
    @staticmethod
    def parse_rate(rate_str: str) -> Tuple[bool, float, float]: ...

class FSM:
    def __init__(self) -> None: ...
    def set_state(self, key: str, state: str, ttl_seconds: float = ...) -> None: ...
    def get_state(self, key: str) -> str: ...
    def clear_state(self, key: str) -> None: ...
    def set_data(self, key: str, data_key: str, data_val: str, ttl_seconds: float = ...) -> None: ...
    def get_data(self, key: str, data_key: str) -> str: ...
    def get_all_data(self, key: str) -> Dict[str, str]: ...
    def set_all_data(self, key: str, data: Dict[str, str], ttl_seconds: float = ...) -> None: ...
    def clear_data(self, key: str) -> None: ...
    def reset(self, key: str = ...) -> None: ...
    def size(self) -> int: ...
    def cleanup_expired(self) -> int: ...

class Cache:
    def __init__(self) -> None: ...
    def set(self, key: str, value: str, ttl_seconds: float = ...) -> None: ...
    def get(self, key: str) -> str: ...
    def has(self, key: str) -> bool: ...
    def delete(self, key: str) -> bool: ...
    def clear(self) -> None: ...
    def size(self) -> int: ...
    def cleanup_expired(self) -> int: ...
    def keys(self) -> List[str]: ...

class WebhookServer:
    def __init__(self) -> None: ...
    def add_route(self, path: str, handler: Callable[[str, str, str], str]) -> None: ...
    def set_default_handler(self, handler: Callable[[str, str, str], str]) -> None: ...
    def start(self, host: str = ..., port: int = ...) -> bool: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def get_port(self) -> int: ...
    def get_host(self) -> str: ...

class AntiSpam:
    def __init__(self, bloom_size: int = ..., window_seconds: float = ...) -> None: ...
    def is_duplicate(self, text: str, user_id: str = ...) -> bool: ...
    def add(self, text: str, user_id: str = ...) -> None: ...
    def calculate_score(self, text: str, message_rate: float = ..., duplicate_count: int = ...) -> float: ...
    def is_spam(self, text: str, threshold: float = ..., message_rate: float = ...) -> bool: ...
    def reset(self) -> None: ...

class Metrics:
    def __init__(self) -> None: ...
    def increment_counter(self, name: str, value: float = ..., labels: Optional[Dict[str, str]] = ...) -> None: ...
    def observe(self, name: str, value: float, labels: Optional[Dict[str, str]] = ...) -> None: ...
    def record_latency(self, command_name: str, duration_seconds: float) -> None: ...
    def export_prometheus(self) -> str: ...
    def reset(self) -> None: ...
