"""
Terminal UI for ``aion.cli_agent`` (imported as ``aion.cli_agent.ui``).

Submodules: ``style``, ``console``, ``aion_shell``, ``menus``, ``messages``, ``status``, ``help``.
"""

from __future__ import annotations

from .glitch import AION_LOGO_LINES, show_aion_glitch_intro
from .aion_shell import (
    aion_input_prompt,
    print_aion_dashboard,
    print_input_area,
    print_shortcuts,
    write_aion_md,
)
from .console import (
    AION_LOGO,
    clear_screen,
    divider,
    print_header,
    print_logo,
    print_agent_tagline,
    run_agent_intro,
    show_aion_boot,
    show_aion_loading,
    show_loading_animation,
    show_spinner,
    type_text,
)
from .help import (
    print_agent_commands,
    print_help_catalog,
    print_interactive_help,
    print_startup_guide,
)
from .slash_help import print_slash_help
from .menus import get_menu_choice, get_yes_no, print_menu, prompt_text
from .messages import (
    agent_print,
    coming_soon_banner,
    error_print,
    provider_error_print,
    info_print,
    success_print,
    tool_print,
    user_input_prompt,
)
from .status import AgentSession, format_status_line, print_session_footer, print_status_bar, spinner_label
from .style import (
    AION_BRAND_HEX,
    COLOR,
    ICON_AGENT,
    ICON_AUTH,
    ICON_CHAT,
    ICON_CODE,
    ICON_CONFIG,
    ICON_ERROR,
    ICON_EXIT,
    ICON_GLOBE,
    ICON_GOOGLE,
    ICON_INFO,
    ICON_LOGOUT,
    ICON_OLLAMA,
    ICON_OFFLINE,
    ICON_RESET,
    ICON_SUCCESS,
    ICON_THINK,
    ICON_TOOL,
    ICON_TRUST,
    ICON_USER,
    ICON_WARNING,
    PROVIDER_ICONS,
    accent,
    accent_bright,
    accent_dim,
    accent_muted,
    bold,
    blue,
    c,
    cyan,
    dim,
    green,
    italic,
    magenta,
    pad_visible,
    red,
    terracotta,
    yellow,
)

__all__ = [
    "AION_BRAND_HEX",
    "AION_LOGO",
    "AION_LOGO_LINES",
    "show_aion_glitch_intro",
    "COLOR",
    "accent",
    "accent_bright",
    "accent_dim",
    "accent_muted",
    "pad_visible",
    "AgentSession",
    "PROVIDER_ICONS",
    "agent_print",
    "bold",
    "blue",
    "c",
    "clear_screen",
    "coming_soon_banner",
    "cyan",
    "dim",
    "divider",
    "error_print",
    "provider_error_print",
    "format_status_line",
    "get_menu_choice",
    "get_yes_no",
    "green",
    "info_print",
    "italic",
    "magenta",
    "print_agent_commands",
    "print_header",
    "print_logo",
    "print_help_catalog",
    "print_agent_tagline",
    "run_agent_intro",
    "show_aion_boot",
    "show_loading_animation",
    "print_interactive_help",
    "print_menu",
    "print_session_footer",
    "print_startup_guide",
    "print_status_bar",
    "prompt_text",
    "red",
    "show_spinner",
    "spinner_label",
    "success_print",
    "tool_print",
    "aion_input_prompt",
    "print_aion_dashboard",
    "print_input_area",
    "print_shortcuts",
    "print_slash_help",
    "write_aion_md",
    "show_aion_loading",
    "type_text",
    "user_input_prompt",
    "yellow",
    # Icons (backward compatible)
    "ICON_AGENT",
    "ICON_AUTH",
    "ICON_CHAT",
    "ICON_CODE",
    "ICON_CONFIG",
    "ICON_ERROR",
    "ICON_EXIT",
    "ICON_GLOBE",
    "ICON_GOOGLE",
    "ICON_INFO",
    "ICON_LOGOUT",
    "ICON_OLLAMA",
    "ICON_OFFLINE",
    "ICON_RESET",
    "ICON_SUCCESS",
    "ICON_THINK",
    "ICON_TOOL",
    "ICON_TRUST",
    "ICON_USER",
    "ICON_WARNING",
]
