"""
Algorithms Package
==================

Public algorithmic utilities with a searchable catalog of 500+ functions.
"""

from .catalog import (
    AlgorithmEntry,
    categories,
    count_algorithms,
    get_algorithm,
    list_algorithms,
    register_algorithm,
)
from ._registry import load_all

load_all()

# search.py — curated exports
from .search import (
    binary_search,
    lower_bound,
    upper_bound,
    is_sorted,
    jump_search,
    find_all_peaks,
    exponential_search,
    linear_search,
    first_occurrence,
    last_occurrence,
    first_last_occurrence,
    rotated_search,
    ternary_search,
    interpolation_search,
    integer_sqrt,
    nth_root,
    kmp_search,
    aho_corasick_simple,
    quickselect,
    find_median_unordered,
)

from .arrays import (
    flatten_array,
    chunk_array,
    remove_duplicates,
    moving_average,
    flatten_deep,
    sliding_window,
    pad_array,
    rolling_sum,
    pairwise,
    matrix_transpose,
    matrix_multiply,
    z_score_normalization,
    min_max_scaling,
)

from .graphs import (
    bfs,
    dfs,
    toposort,
    dijkstra,
    a_star_search as a_star,
    bellman_ford,
    floyd_warshall,
    tarjan_scc,
    kosaraju_scc,
    prim_mst,
    kruskal_mst,
    ford_fulkerson,
    page_rank_simple as pagerank,
    connected_components,
)

__all__ = [
    "AlgorithmEntry",
    "categories",
    "count_algorithms",
    "get_algorithm",
    "list_algorithms",
    "register_algorithm",
    "binary_search",
    "lower_bound",
    "upper_bound",
    "is_sorted",
    "jump_search",
    "find_all_peaks",
    "exponential_search",
    "linear_search",
    "first_occurrence",
    "last_occurrence",
    "first_last_occurrence",
    "rotated_search",
    "ternary_search",
    "interpolation_search",
    "integer_sqrt",
    "nth_root",
    "kmp_search",
    "aho_corasick_simple",
    "quickselect",
    "find_median_unordered",
    "flatten_array",
    "chunk_array",
    "remove_duplicates",
    "moving_average",
    "flatten_deep",
    "sliding_window",
    "pad_array",
    "rolling_sum",
    "pairwise",
    "matrix_transpose",
    "matrix_multiply",
    "z_score_normalization",
    "min_max_scaling",
    "bfs",
    "dfs",
    "toposort",
    "dijkstra",
    "a_star",
    "bellman_ford",
    "floyd_warshall",
    "tarjan_scc",
    "kosaraju_scc",
    "prim_mst",
    "kruskal_mst",
    "ford_fulkerson",
    "pagerank",
    "connected_components",
]
