# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Sum of Numeric Vector
#' @param x Numeric vector
#' @return Sum of the vector elements
#' @examples
#' pytekt_sum(c(1.0, 2.0, 3.0, 4.0))
#' @export
pytekt_sum <- function(x) {
    .Call(`_pytekt_pytekt_sum`, x)
}

#' Fast Mean
#' @param x Numeric vector
#' @return Arithmetic mean of vector elements
#' @examples
#' pytekt_mean(c(1.0, 2.0, 3.0, 4.0))
#' @export
pytekt_mean <- function(x) {
    .Call(`_pytekt_pytekt_mean`, x)
}

#' Fast Variance
#' @param x Numeric vector
#' @param ddof Delta degrees of freedom (default: 0)
#' @return Variance of the vector
#' @examples
#' pytekt_variance(c(1.0, 2.0, 3.0, 4.0), ddof = 1)
#' @export
pytekt_variance <- function(x, ddof = 0L) {
    .Call(`_pytekt_pytekt_variance`, x, ddof)
}

#' Fast Standard Deviation
#' @param x Numeric vector
#' @param ddof Delta degrees of freedom (default: 0)
#' @return Standard deviation of the vector
#' @examples
#' pytekt_std(c(1.0, 2.0, 3.0, 4.0), ddof = 1)
#' @export
pytekt_std <- function(x, ddof = 0L) {
    .Call(`_pytekt_pytekt_std`, x, ddof)
}

#' Fast Minimum
#' @param x Numeric vector
#' @return Minimum value in vector
#' @examples
#' pytekt_min(c(4.0, 1.0, 8.0, 2.0))
#' @export
pytekt_min <- function(x) {
    .Call(`_pytekt_pytekt_min`, x)
}

#' Fast Maximum
#' @param x Numeric vector
#' @return Maximum value in vector
#' @examples
#' pytekt_max(c(4.0, 1.0, 8.0, 2.0))
#' @export
pytekt_max <- function(x) {
    .Call(`_pytekt_pytekt_max`, x)
}

#' Fast Argmin (1-indexed)
#' @param x Numeric vector
#' @return 1-based index of minimum element
#' @examples
#' pytekt_argmin(c(4.0, 1.0, 8.0, 2.0))
#' @export
pytekt_argmin <- function(x) {
    .Call(`_pytekt_pytekt_argmin`, x)
}

#' Fast Argmax (1-indexed)
#' @param x Numeric vector
#' @return 1-based index of maximum element
#' @examples
#' pytekt_argmax(c(4.0, 1.0, 8.0, 2.0))
#' @export
pytekt_argmax <- function(x) {
    .Call(`_pytekt_pytekt_argmax`, x)
}

#' Fast Dot Product of Two Vectors
#' @param a First numeric vector
#' @param b Second numeric vector
#' @return Inner dot product
#' @examples
#' pytekt_dot(c(1.0, 2.0), c(3.0, 4.0))
#' @export
pytekt_dot <- function(a, b) {
    .Call(`_pytekt_pytekt_dot`, a, b)
}

#' Fast L2 Norm
#' @param x Numeric vector
#' @return Euclidean L2 norm
#' @examples
#' pytekt_norm2(c(3.0, 4.0))
#' @export
pytekt_norm2 <- function(x) {
    .Call(`_pytekt_pytekt_norm2`, x)
}

#' Fast Euclidean Distance
#' @param a First numeric vector
#' @param b Second numeric vector
#' @return Euclidean distance between a and b
#' @examples
#' pytekt_euclidean_distance(c(0.0, 0.0), c(3.0, 4.0))
#' @export
pytekt_euclidean_distance <- function(a, b) {
    .Call(`_pytekt_pytekt_euclidean_distance`, a, b)
}

#' Fast Cosine Similarity
#' @param a First numeric vector
#' @param b Second numeric vector
#' @return Cosine similarity in range [-1, 1]
#' @examples
#' pytekt_cosine_similarity(c(1.0, 0.0), c(1.0, 1.0))
#' @export
pytekt_cosine_similarity <- function(a, b) {
    .Call(`_pytekt_pytekt_cosine_similarity`, a, b)
}

#' Fast Matrix Multiplication (Row-Major flattened matrices)
#' @param A Flattened matrix A (m x n)
#' @param B Flattened matrix B (n x p)
#' @param m Rows of A
#' @param n Columns of A / Rows of B
#' @param p Columns of B
#' @return Flattened product matrix (m x p)
#' @examples
#' pytekt_matrix_multiply(c(1, 2, 3, 4), c(5, 6, 7, 8), 2, 2, 2)
#' @export
pytekt_matrix_multiply <- function(A, B, m, n, p) {
    .Call(`_pytekt_pytekt_matrix_multiply`, A, B, m, n, p)
}

#' Fast Cumulative Prefix Sum
#' @param x Numeric vector
#' @return Cumulative prefix sum vector
#' @examples
#' pytekt_prefix_sum(c(1.0, 2.0, 3.0, 4.0))
#' @export
pytekt_prefix_sum <- function(x) {
    .Call(`_pytekt_pytekt_prefix_sum`, x)
}

#' Fast Rolling Sum
#' @param x Numeric vector
#' @param window Window size
#' @return Rolling sums
#' @examples
#' pytekt_rolling_sum(c(1.0, 2.0, 3.0, 4.0, 5.0), window = 3)
#' @export
pytekt_rolling_sum <- function(x, window) {
    .Call(`_pytekt_pytekt_rolling_sum`, x, window)
}

#' Fast Rolling Mean
#' @param x Numeric vector
#' @param window Window size
#' @return Rolling means
#' @examples
#' pytekt_rolling_mean(c(1.0, 2.0, 3.0, 4.0, 5.0), window = 3)
#' @export
pytekt_rolling_mean <- function(x, window) {
    .Call(`_pytekt_pytekt_rolling_mean`, x, window)
}

#' Fast Streaming Histogram
#' @param x Numeric vector
#' @param bins Number of bins
#' @param lo Lower bound
#' @param hi Upper bound
#' @return Integer bin counts
#' @examples
#' pytekt_histogram(c(1.0, 2.0, 3.0, 4.0, 5.0), bins = 5, lo = 1.0, hi = 5.0)
#' @export
pytekt_histogram <- function(x, bins, lo, hi) {
    .Call(`_pytekt_pytekt_histogram`, x, bins, lo, hi)
}

#' Fast Chunk Statistics
#' @param x Numeric vector
#' @param chunk_size Size of each chunk
#' @return A list with `mean`, `min`, `max`, and `chunk_size`
#' @examples
#' pytekt_chunk_statistics(c(1.0, 2.0, 3.0, 4.0, 5.0, 6.0), chunk_size = 2)
#' @export
pytekt_chunk_statistics <- function(x, chunk_size) {
    .Call(`_pytekt_pytekt_chunk_statistics`, x, chunk_size)
}

