# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Sum of Numeric Vector
#' @param x Numeric vector
#' @export
aion_sum <- function(x) {
    .Call(`_aion_aion_sum`, x)
}

#' Fast Dot Product of Two Vectors
#' @param a First numeric vector
#' @param b Second numeric vector
#' @export
aion_dot <- function(a, b) {
    .Call(`_aion_aion_dot`, a, b)
}

#' Fast L2 Norm
#' @param x Numeric vector
#' @export
aion_norm2 <- function(x) {
    .Call(`_aion_aion_norm2`, x)
}

#' Fast Mean
#' @param x Numeric vector
#' @export
aion_mean <- function(x) {
    .Call(`_aion_aion_mean`, x)
}

#' Fast Variance
#' @param x Numeric vector
#' @param ddof Delta degrees of freedom (default: 0)
#' @export
aion_variance <- function(x, ddof = 0L) {
    .Call(`_aion_aion_variance`, x, ddof)
}

#' Fast Matrix Multiplication (Row-Major flattened matrices)
#' @param A Flattened matrix A (m x n)
#' @param B Flattened matrix B (n x p)
#' @param m Rows of A
#' @param n Columns of A / Rows of B
#' @param p Columns of B
#' @export
aion_matrix_multiply <- function(A, B, m, n, p) {
    .Call(`_aion_aion_matrix_multiply`, A, B, m, n, p)
}

#' Fast Cumulative Prefix Sum
#' @param x Numeric vector
#' @export
aion_prefix_sum <- function(x) {
    .Call(`_aion_aion_prefix_sum`, x)
}

#' Fast Rolling Sum
#' @param x Numeric vector
#' @param window Window size
#' @export
aion_rolling_sum <- function(x, window) {
    .Call(`_aion_aion_rolling_sum`, x, window)
}

#' Fast Rolling Mean
#' @param x Numeric vector
#' @param window Window size
#' @export
aion_rolling_mean <- function(x, window) {
    .Call(`_aion_aion_rolling_mean`, x, window)
}

#' Fast Streaming Histogram
#' @param x Numeric vector
#' @param bins Number of bins
#' @param lo Lower bound
#' @param hi Upper bound
#' @export
aion_histogram <- function(x, bins, lo, hi) {
    .Call(`_aion_aion_histogram`, x, bins, lo, hi)
}

