"""
aion.maths.linear_algebra
=========================

Linear algebra helpers organised into one flat namespace.

All functions live in ``matrix.py`` — a single, self-contained file with
100+ functions across 12 categories:

    1.  Standard Generators      zeros, ones, eye, identity, full, arange_matrix …
    2.  Diagonal & Triangular    diag, triu, tril, tridiagonal, block_diag …
    3.  Random Matrices          random_uniform, random_normal, random_sparse …
    4.  Special Matrices         hilbert, toeplitz, vandermonde, hadamard_matrix …
    5.  Element-wise Operations  matrix_add, matrix_scale, apply_function …
    6.  Core Linear Algebra      matrix_multiply, determinant, matrix_inverse …
    7.  Decompositions           lu_decomposition, qr_decomposition, svd …
    8.  Solvers & Properties     solve_linear_system, is_symmetric …
    9.  Reshaping & Slicing      reshape_matrix, hstack, vstack, kron …
   10.  Geometric / 3-D          rotation_matrix_2d, perspective_projection_matrix …
   11.  Analysis & Statistics    matrix_norm, matrix_mean, matrix_density …
   12.  Custom Builders          create_matrix_from_rule, CustomMatrixBuilder …

Quick usage::

    from aion.maths.linear_algebra import zeros, matrix_multiply, svd
    from aion.maths.linear_algebra import CustomMatrixBuilder, create_matrix_from_rule
"""

from .matrix import *  # noqa: F401, F403
from .vectors import *  # noqa: F401, F403
from .matrix import __all__ as _matrix_all
from .vectors import __all__ as _vectors_all

__all__ = list(_matrix_all) + list(_vectors_all)
