"""HTML page builder — dark-themed reports and dashboards (stdlib only)."""

from __future__ import annotations

import html as html_module
from pathlib import Path
from typing import Any, List, Optional, Sequence, Union

PathLike = Union[str, Path]

_BASE_CSS = """
:root {
  --bg: #0a0e14; --surface: #131921; --card: #1a2332; --border: #2d3a4d;
  --text: #e7edf4; --muted: #8b9cb3; --accent: #3d8bfd; --accent2: #3ecf8e;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: ui-sans-serif, system-ui, sans-serif;
  background: var(--bg); color: var(--text);
  line-height: 1.6; padding: 1.5rem; max-width: 1200px; margin: 0 auto;
}
header { margin-bottom: 1.5rem; padding-bottom: 1rem; border-bottom: 1px solid var(--border); }
h1 { font-size: 1.75rem; font-weight: 700; }
.subtitle { color: var(--muted); margin-top: 0.35rem; }
h2 { font-size: 1.1rem; margin: 1.25rem 0 0.65rem; color: var(--accent); font-weight: 600; }
p { margin: 0.5rem 0; color: var(--muted); }
.metrics {
  display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 0.75rem; margin: 0.75rem 0;
}
.metric {
  background: var(--surface); border: 1px solid var(--border);
  border-radius: 8px; padding: 0.75rem; text-align: center;
}
.metric .val { font-size: 1.35rem; font-weight: 700; color: var(--accent2); }
.metric .lbl { font-size: 0.75rem; color: var(--muted); text-transform: uppercase; }
table { width: 100%; border-collapse: collapse; font-size: 0.875rem; }
th, td { text-align: left; padding: 0.5rem 0.65rem; border-bottom: 1px solid var(--border); }
th { color: var(--muted); }
pre {
  background: rgba(0,0,0,0.35); border-radius: 8px; padding: 0.85rem;
  overflow-x: auto; font-family: monospace; font-size: 0.82rem;
}
.figure-wrap img { max-width: 100%; border-radius: 8px; border: 1px solid var(--border); }
footer {
  margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border);
  font-size: 0.8rem; color: var(--muted);
}
"""


def escape_html(text: Any) -> str:
    """Escape text for safe HTML embedding."""
    return html_module.escape(str(text))


def metrics_row_html(metrics: dict) -> str:
    """Render a row of metric cards."""
    lines = ['<div class="metrics">']
    for key, val in metrics.items():
        display = f"{val:.4g}" if isinstance(val, float) else escape_html(val)
        lbl = escape_html(key)
        lines.append(
            f'<div class="metric"><div class="val">{display}</div>'
            f'<div class="lbl">{lbl}</div></div>'
        )
    lines.append("</div>")
    return "\n".join(lines)

def table_html(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> str:
    """Render an HTML table."""
    h = "".join(f"<th>{escape_html(x)}</th>" for x in headers)
    body_rows = []
    for row in rows:
        cells = "".join(f"<td>{escape_html(c)}</td>" for c in row)
        body_rows.append(f"<tr>{cells}</tr>")
    return f"<table><thead><tr>{h}</tr></thead><tbody>{''.join(body_rows)}</tbody></table>"


class PageBuilder:
    """Build a self-contained HTML report page."""

    def __init__(
        self,
        title: str,
        *,
        subtitle: str = "",
        footer: str = "Generated by Aqwel-Aion",
    ) -> None:
        self.title = title
        self.subtitle = subtitle
        self.footer = footer
        self._blocks: List[str] = []

    def add_heading(self, text: str, level: int = 2) -> "PageBuilder":
        tag = f"h{min(max(level, 1), 6)}"
        self._blocks.append(f"<{tag}>{escape_html(text)}</{tag}>")
        return self

    def add_paragraph(self, text: str) -> "PageBuilder":
        self._blocks.append(f"<p>{escape_html(text)}</p>")
        return self

    def add_metrics(self, metrics: dict) -> "PageBuilder":
        self._blocks.append(metrics_row_html(metrics))
        return self

    def add_table(
        self, headers: Sequence[str], rows: Sequence[Sequence[Any]]
    ) -> "PageBuilder":
        self._blocks.append(table_html(headers, rows))
        return self

    def add_code(self, code: str) -> "PageBuilder":
        self._blocks.append(f"<pre>{escape_html(code)}</pre>")
        return self

    def add_html(self, fragment: str) -> "PageBuilder":
        self._blocks.append(fragment)
        return self

    def add_figures(self, figures: Sequence[Any], *, fmt: str = "png") -> "PageBuilder":
        try:
            from aion.visualization.report import figures_to_html_img_tags

            imgs = figures_to_html_img_tags(figures, fmt=fmt)
            self._blocks.append('<div class="figure-wrap">' + imgs + "</div>")
        except Exception as exc:
            self._blocks.append(f"<p><em>Figures unavailable: {escape_html(exc)}</em></p>")
        return self

    def build(self) -> str:
        sub = (
            '<p class="subtitle">' + escape_html(self.subtitle) + "</p>"
            if self.subtitle
            else ""
        )
        body = "\n".join(self._blocks)
        title = escape_html(self.title)
        foot = escape_html(self.footer)
        return (
            '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/>'
            '<meta name="viewport" content="width=device-width, initial-scale=1"/>'
            "<title>" + title + "</title><style>" + _BASE_CSS + "</style></head><body>"
            "<header><h1>" + title + "</h1>" + sub + "</header><main>"
            + body
            + "</main><footer>"
            + foot
            + "</footer></body></html>"
        )

    def save(self, path: PathLike) -> str:
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.build(), encoding="utf-8")
        return str(path)
