// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// aion_sum
double aion_sum(NumericVector x);
RcppExport SEXP _aion_aion_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// aion_dot
double aion_dot(NumericVector a, NumericVector b);
RcppExport SEXP _aion_aion_dot(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_dot(a, b));
    return rcpp_result_gen;
END_RCPP
}
// aion_norm2
double aion_norm2(NumericVector x);
RcppExport SEXP _aion_aion_norm2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_norm2(x));
    return rcpp_result_gen;
END_RCPP
}
// aion_mean
double aion_mean(NumericVector x);
RcppExport SEXP _aion_aion_mean(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_mean(x));
    return rcpp_result_gen;
END_RCPP
}
// aion_variance
double aion_variance(NumericVector x, int ddof);
RcppExport SEXP _aion_aion_variance(SEXP xSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_variance(x, ddof));
    return rcpp_result_gen;
END_RCPP
}
// aion_matrix_multiply
NumericVector aion_matrix_multiply(NumericVector A, NumericVector B, int m, int n, int p);
RcppExport SEXP _aion_aion_matrix_multiply(SEXP ASEXP, SEXP BSEXP, SEXP mSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_matrix_multiply(A, B, m, n, p));
    return rcpp_result_gen;
END_RCPP
}
// aion_prefix_sum
NumericVector aion_prefix_sum(NumericVector x);
RcppExport SEXP _aion_aion_prefix_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_prefix_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// aion_rolling_sum
NumericVector aion_rolling_sum(NumericVector x, int window);
RcppExport SEXP _aion_aion_rolling_sum(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_rolling_sum(x, window));
    return rcpp_result_gen;
END_RCPP
}
// aion_rolling_mean
NumericVector aion_rolling_mean(NumericVector x, int window);
RcppExport SEXP _aion_aion_rolling_mean(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_rolling_mean(x, window));
    return rcpp_result_gen;
END_RCPP
}
// aion_histogram
IntegerVector aion_histogram(NumericVector x, int bins, double lo, double hi);
RcppExport SEXP _aion_aion_histogram(SEXP xSEXP, SEXP binsSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type bins(binsSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(aion_histogram(x, bins, lo, hi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aion_aion_sum", (DL_FUNC) &_aion_aion_sum, 1},
    {"_aion_aion_dot", (DL_FUNC) &_aion_aion_dot, 2},
    {"_aion_aion_norm2", (DL_FUNC) &_aion_aion_norm2, 1},
    {"_aion_aion_mean", (DL_FUNC) &_aion_aion_mean, 1},
    {"_aion_aion_variance", (DL_FUNC) &_aion_aion_variance, 2},
    {"_aion_aion_matrix_multiply", (DL_FUNC) &_aion_aion_matrix_multiply, 5},
    {"_aion_aion_prefix_sum", (DL_FUNC) &_aion_aion_prefix_sum, 1},
    {"_aion_aion_rolling_sum", (DL_FUNC) &_aion_aion_rolling_sum, 2},
    {"_aion_aion_rolling_mean", (DL_FUNC) &_aion_aion_rolling_mean, 2},
    {"_aion_aion_histogram", (DL_FUNC) &_aion_aion_histogram, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_aion(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
