// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pytekt_sum
double pytekt_sum(NumericVector x);
RcppExport SEXP _pytekt_pytekt_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_mean
double pytekt_mean(NumericVector x);
RcppExport SEXP _pytekt_pytekt_mean(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_mean(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_variance
double pytekt_variance(NumericVector x, int ddof);
RcppExport SEXP _pytekt_pytekt_variance(SEXP xSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_variance(x, ddof));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_std
double pytekt_std(NumericVector x, int ddof);
RcppExport SEXP _pytekt_pytekt_std(SEXP xSEXP, SEXP ddofSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type ddof(ddofSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_std(x, ddof));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_min
double pytekt_min(NumericVector x);
RcppExport SEXP _pytekt_pytekt_min(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_min(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_max
double pytekt_max(NumericVector x);
RcppExport SEXP _pytekt_pytekt_max(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_max(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_argmin
int pytekt_argmin(NumericVector x);
RcppExport SEXP _pytekt_pytekt_argmin(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_argmin(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_argmax
int pytekt_argmax(NumericVector x);
RcppExport SEXP _pytekt_pytekt_argmax(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_argmax(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_dot
double pytekt_dot(NumericVector a, NumericVector b);
RcppExport SEXP _pytekt_pytekt_dot(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_dot(a, b));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_norm2
double pytekt_norm2(NumericVector x);
RcppExport SEXP _pytekt_pytekt_norm2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_norm2(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_euclidean_distance
double pytekt_euclidean_distance(NumericVector a, NumericVector b);
RcppExport SEXP _pytekt_pytekt_euclidean_distance(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_euclidean_distance(a, b));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_cosine_similarity
double pytekt_cosine_similarity(NumericVector a, NumericVector b);
RcppExport SEXP _pytekt_pytekt_cosine_similarity(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_cosine_similarity(a, b));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_matrix_multiply
NumericVector pytekt_matrix_multiply(NumericVector A, NumericVector B, int m, int n, int p);
RcppExport SEXP _pytekt_pytekt_matrix_multiply(SEXP ASEXP, SEXP BSEXP, SEXP mSEXP, SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_matrix_multiply(A, B, m, n, p));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_prefix_sum
NumericVector pytekt_prefix_sum(NumericVector x);
RcppExport SEXP _pytekt_pytekt_prefix_sum(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_prefix_sum(x));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_rolling_sum
NumericVector pytekt_rolling_sum(NumericVector x, int window);
RcppExport SEXP _pytekt_pytekt_rolling_sum(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_rolling_sum(x, window));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_rolling_mean
NumericVector pytekt_rolling_mean(NumericVector x, int window);
RcppExport SEXP _pytekt_pytekt_rolling_mean(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_rolling_mean(x, window));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_histogram
IntegerVector pytekt_histogram(NumericVector x, int bins, double lo, double hi);
RcppExport SEXP _pytekt_pytekt_histogram(SEXP xSEXP, SEXP binsSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type bins(binsSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_histogram(x, bins, lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// pytekt_chunk_statistics
List pytekt_chunk_statistics(NumericVector x, int chunk_size);
RcppExport SEXP _pytekt_pytekt_chunk_statistics(SEXP xSEXP, SEXP chunk_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pytekt_chunk_statistics(x, chunk_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pytekt_pytekt_sum", (DL_FUNC) &_pytekt_pytekt_sum, 1},
    {"_pytekt_pytekt_mean", (DL_FUNC) &_pytekt_pytekt_mean, 1},
    {"_pytekt_pytekt_variance", (DL_FUNC) &_pytekt_pytekt_variance, 2},
    {"_pytekt_pytekt_std", (DL_FUNC) &_pytekt_pytekt_std, 2},
    {"_pytekt_pytekt_min", (DL_FUNC) &_pytekt_pytekt_min, 1},
    {"_pytekt_pytekt_max", (DL_FUNC) &_pytekt_pytekt_max, 1},
    {"_pytekt_pytekt_argmin", (DL_FUNC) &_pytekt_pytekt_argmin, 1},
    {"_pytekt_pytekt_argmax", (DL_FUNC) &_pytekt_pytekt_argmax, 1},
    {"_pytekt_pytekt_dot", (DL_FUNC) &_pytekt_pytekt_dot, 2},
    {"_pytekt_pytekt_norm2", (DL_FUNC) &_pytekt_pytekt_norm2, 1},
    {"_pytekt_pytekt_euclidean_distance", (DL_FUNC) &_pytekt_pytekt_euclidean_distance, 2},
    {"_pytekt_pytekt_cosine_similarity", (DL_FUNC) &_pytekt_pytekt_cosine_similarity, 2},
    {"_pytekt_pytekt_matrix_multiply", (DL_FUNC) &_pytekt_pytekt_matrix_multiply, 5},
    {"_pytekt_pytekt_prefix_sum", (DL_FUNC) &_pytekt_pytekt_prefix_sum, 1},
    {"_pytekt_pytekt_rolling_sum", (DL_FUNC) &_pytekt_pytekt_rolling_sum, 2},
    {"_pytekt_pytekt_rolling_mean", (DL_FUNC) &_pytekt_pytekt_rolling_mean, 2},
    {"_pytekt_pytekt_histogram", (DL_FUNC) &_pytekt_pytekt_histogram, 4},
    {"_pytekt_pytekt_chunk_statistics", (DL_FUNC) &_pytekt_pytekt_chunk_statistics, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_pytekt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
